SSH_KEY_PATH="/path/to/ssh/key" # example: /Users/my-username/.ssh/my-ssh-key

HOST_USERNAME="ec2-user"
HOST_USER_HOME="/home/${HOST_USERNAME}"
EXTERNAL_VOLUME_AWS_VOLUME_ID="vol-xxxxxxxx"
EXTERNAL_VOLUME_DEVICE_NAME="/dev/xvdf"
EXTERNAL_VOLUME_MOUNT_POINT="${HOST_USER_HOME}/external-volume"

HOST_PATH_CONTENTS_ROOT="${EXTERNAL_VOLUME_MOUNT_POINT}/contents"

HOST_PATH_NOHUP_LOG_FILE="${HOST_PATH_CONTENTS_ROOT}/nohup_out.log"

HOST_PATH_DOCKER_ROOT="${HOST_PATH_CONTENTS_ROOT}/docker_root"
HOST_PATH_DOCKER_IMAGE_SOURCE="${HOST_PATH_CONTENTS_ROOT}/docker_image_source"
DOCKER_CONTAINER_NAME="agent_trainer_container"

FOLDER_AGENT_TRAINER="agent_trainer"
FOLDER_AGENT_GAME_EMULATOR_SOURCE="game_emulator_source"
FOLDER_AGENT_TRAIN_RESULTS="train_results"

HOST_PATH_DOCKER_SHARE="${HOST_PATH_CONTENTS_ROOT}/docker_share"
HOST_PATH_AGENT_TRAINER="${HOST_PATH_DOCKER_SHARE}/${FOLDER_AGENT_TRAINER}"
HOST_PATH_GAME_EMULATOR_SOURCE="${HOST_PATH_DOCKER_SHARE}/${FOLDER_AGENT_GAME_EMULATOR_SOURCE}"
HOST_PATH_TRAIN_RESULTS="${HOST_PATH_DOCKER_SHARE}/${FOLDER_AGENT_TRAIN_RESULTS}"

CONTAINER_PATH_DOCKER_SHARE="/shared"
CONTAINER_PATH_AGENT_TRAINER="${CONTAINER_PATH_DOCKER_SHARE}/${FOLDER_AGENT_TRAINER}"
CONTAINER_PATH_GAME_EMULATOR_SOURCE="${CONTAINER_PATH_DOCKER_SHARE}/${FOLDER_AGENT_GAME_EMULATOR_SOURCE}"
CONTAINER_PATH_TRAIN_RESULTS="${CONTAINER_PATH_DOCKER_SHARE}/${FOLDER_AGENT_TRAIN_RESULTS}"

USE_GPU=true

if [ "$USE_GPU" = true ] ; then
    DOCKER_RUNNER="nvidia-docker"
    DOCKERFILE_PATH="${HOST_PATH_DOCKER_IMAGE_SOURCE}/Dockerfile.gpu"
    DOCKER_IMAGE_NAME="lopespm/agent-trainer-gpu"
else
    DOCKER_RUNNER="docker"
    DOCKERFILE_PATH="${HOST_PATH_DOCKER_IMAGE_SOURCE}/Dockerfile.cpu"
    DOCKER_IMAGE_NAME="lopespm/agent-trainer-cpu"
fi
